# SYNAPSE - A Gateway of Intelligent Perception for Traffic Management
# Copyright (C) 2026 Noxfort Systems
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# File: src/slm/output_sanitizer.py
# Author: Gabriel Moraes
# Date: 2026-09-03

import re


class SLMOutputSanitizer:
    """
    Sanitizes raw output strings generated by LLMs:
    Removes thinking blocks (<think>...</think>), emojis, backticks, stray formatting,
    and trailing spaces before punctuation for strict municipal engineering audit standards.
    Adheres to the CARINA SLM architecture pattern.
    """

    @staticmethod
    def sanitize(raw_text: str) -> str:
        """Cleans think blocks, graphic emojis, stray backticks, and extra whitespace."""
        if not raw_text:
            return ""

        # 1. Clean thinking blocks (<think>...</think>), including enclosing markdown blocks if present
        text = re.sub(r"```[a-zA-Z]*\s*<think>.*?</think>\s*```", "", raw_text, flags=re.DOTALL)
        text = re.sub(r"<think>.*?</think>", "", text, flags=re.DOTALL)
        text = re.sub(r"<think>.*", "", text, flags=re.DOTALL).strip()
        text = text.replace("</think>", "")
        text = re.sub(r"^\s*`+\s*", "", text)
        text = re.sub(r"\s*`+\s*$", "", text)

        # 2. Strict post-processing removal of any emojis or graphic symbols
        emoji_pattern = re.compile(
            r"[\U00010000-\U0010ffff\u2600-\u27ff\u2300-\u23ff\u2b50\u2b55\u200d\ufe0f]",
            flags=re.UNICODE
        )
        text = emoji_pattern.sub("", text)

        # 3. Clean spaces before punctuation caused by removed tokens/emojis
        text = re.sub(r"\s+([.,;:!?])", r"\1", text)
        text = re.sub(r"[ \t]+", " ", text)

        # 4. Clean trailing repetitive whitespace
        text = re.sub(r"\n{3,}", "\n\n", text)

        return text.strip()
