# SYNAPSE - A Gateway of Intelligent Perception for Traffic Management
# Copyright (C) 2025 Noxfort Systems
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# File: src/services/fenix_service.py
# Author: Gabriel Moraes
# Date: 2025-12-18

import os
import json
import time
import threading
import traceback
from datetime import datetime
from enum import Enum
from typing import Dict, Optional
from pathlib import Path

from PyQt6.QtCore import QObject, pyqtSignal, pyqtSlot, QTimer

# Import Domain & Utils
from src.utils.logging_setup import logger
from src.managers.storage_manager import StorageManager
from src.domain.app_state import AppState

class TriggerType(Enum):
    MANUAL = 0
    OPPORTUNISTIC = 1  
    EMERGENCY = 2      

class FenixService(QObject):
    """
    F.E.N.I.X. Service (Fail-safe Evolutionary Neural Inference eXchange).
    
    V30 Architecture (Updated Path):
    - Reads schedule from 'Synapse/data/maintenance_schedule.json'.
    - Lightweight orchestration (No PyTorch).
    """

    # --- Signals ---
    cycle_started = pyqtSignal(str)              
    cycle_finished = pyqtSignal(bool, str)       
    progress_update = pyqtSignal(str, int)       
    
    # Critical System Commands
    request_fallback_activation = pyqtSignal(bool) 
    request_model_hot_swap = pyqtSignal(str)       
    
    def __init__(self, storage_manager: StorageManager, app_state: AppState):
        super().__init__()
        self.storage = storage_manager
        self.app_state = app_state
        self.is_running = False
        self.stop_requested = False
        self.is_monitoring_active = False 
        
        # Monitoring Config
        self.reconstruction_threshold = 0.30 
        
        # UPDATED PATH
        self.schedule_path = Path("Synapse/data/maintenance_schedule.json")
        self.schedule_map = {} 

        # Worker Thread
        self.worker_thread = None
        
        # Scheduler Timer (Checks every 10 minutes)
        self.scheduler = QTimer(self)
        self.scheduler.timeout.connect(self._check_opportunity)
        
        logger.info("[FENIX] Service initialized (Lightweight Mode). Waiting for Phase 2 activation.")

    def activate_monitoring(self):
        """
        Called by MainController when Phase 2 (Online Operation) begins.
        Loads the JSON schedule and starts the timer.
        """
        if self.is_monitoring_active:
            return

        logger.info("[FENIX] 🟢 Activating Opportunity Scanner...")
        
        # 1. Load the Static Schedule (Generated by OfflineService in Phase 1)
        if self.schedule_path.exists():
            try:
                with open(self.schedule_path, 'r') as f:
                    self.schedule_map = json.load(f)
                logger.info(f"[FENIX] 📅 Maintenance Schedule Loaded from {self.schedule_path} ({len(self.schedule_map)} slots).")
            except Exception as e:
                logger.error(f"[FENIX] Failed to load schedule JSON: {e}")
                self.schedule_map = {}
        else:
            logger.warning(f"[FENIX] ⚠️ Schedule not found at {self.schedule_path}. Opportunistic maintenance disabled.")
            self.schedule_map = {}

        # 2. Start Timer
        self.is_monitoring_active = True
        self.scheduler.start(600000) # 10 Minutes
        
        # Perform immediate check
        QTimer.singleShot(5000, self._check_opportunity)

    def deactivate_monitoring(self):
        """Called when system stops."""
        logger.info("[FENIX] 🔴 Hibernating Opportunity Scanner.")
        self.is_monitoring_active = False
        self.scheduler.stop()

    @pyqtSlot()
    def _check_opportunity(self):
        """
        O(1) Lookup in the JSON map to see if current time is a VALLEY.
        """
        if not self.is_monitoring_active or self.is_running:
            return
            
        now = datetime.now()
        key = f"{now.weekday()}_{now.hour}" # Format: "0_14" (Mon 14h)
        
        # Lookup State (0=VALLEY, 1=NORMAL, 2=PEAK)
        state = self.schedule_map.get(key, 1) 
        
        if state == 0: # 0 is TrafficState.VALLEY
            logger.info(f"[FENIX] 🦅 Opportunity Detected via Schedule (Slot {key}). Initiating Cycle.")
            self.start_fenix_cycle(TriggerType.OPPORTUNISTIC)
        else:
            pass

    @pyqtSlot(float)
    def check_health_metrics(self, current_reconstruction_error: float):
        """Checks for Critical Anomalies (Gatilho B)."""
        if not self.is_monitoring_active or self.is_running:
            return

        if current_reconstruction_error > self.reconstruction_threshold:
            logger.warning(f"[FENIX] ⚠️ EMERGENCY TRIGGER: Reconstruction Error {current_reconstruction_error:.2f} > {self.reconstruction_threshold}")
            self.start_fenix_cycle(TriggerType.EMERGENCY)

    def start_fenix_cycle(self, trigger: TriggerType):
        if self.is_running: return
            
        self.is_running = True
        self.stop_requested = False
        self.cycle_started.emit(f"F.E.N.I.X. Cycle Initiated by {trigger.name}")
        
        self.worker_thread = threading.Thread(target=self._run_phoenix_flight, args=(trigger,))
        self.worker_thread.start()

    def stop_cycle(self):
        self.stop_requested = True

    # --- THE PHOENIX FLIGHT (Orchestration) ---

    def _run_phoenix_flight(self, trigger: TriggerType):
        try:
            logger.info(">>> [FENIX] STARTING REGENERATION CYCLE <<<")
            
            # STEP A: FALLBACK
            self._update_status("Activating Fallback (MEH)...", 10)
            self.request_fallback_activation.emit(True)
            time.sleep(2) 
            
            if self.stop_requested: raise InterruptedError("Cycle Aborted by User")

            # STEP B: RETRAINING
            self._update_status("Loading Data (Last 24h)...", 20)
            time.sleep(1)
            
            if self.stop_requested: raise InterruptedError("Cycle Aborted by User")

            self._update_status("Generating Synthetic Data (PatchTST)...", 35)
            time.sleep(2)
            
            self._update_status("Hyperparameter Check (Optuna)...", 50)
            time.sleep(1)

            # STEP C: WARM START
            self._update_status("Warm Start: Fine-Tuning Neural Network...", 60)
            new_model_path = "temp/candidate_model.pth" 
            time.sleep(5)
            
            if self.stop_requested: raise InterruptedError("Cycle Aborted by User")

            # STEP D: VALIDATION & DEPLOY
            self._update_status("Validating New Model...", 85)
            is_valid = True 
            
            if is_valid:
                self._update_status("Validation PASSED. Hot-Swapping Model...", 95)
                final_path = self.storage.save_model_checkpoint(new_model_path, tag="fenix_autogen")
                self.request_model_hot_swap.emit(final_path)
                result_msg = "Cycle Complete. Model Evolved."
                success = True
            else:
                self._update_status("Validation FAILED. Discarding Candidate.", 95)
                result_msg = "Cycle Complete. Improvement failed; Old model retained."
                success = False

            logger.info("<<< [FENIX] CYCLE FINISHED. RESTORING NORMAL OPS. >>>")
            self.request_fallback_activation.emit(False) 
            self.cycle_finished.emit(success, result_msg)

        except Exception as e:
            logger.error(f"[FENIX] Critical Failure in Cycle: {e}")
            traceback.print_exc()
            self.request_fallback_activation.emit(False) 
            self.cycle_finished.emit(False, f"Error: {str(e)}")
        finally:
            self.is_running = False

    def _update_status(self, msg: str, percent: int):
        logger.info(f"[FENIX] {msg}")
        self.progress_update.emit(msg, percent)