# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import proto.synapse_hft_pb2 as synapse__hft__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in synapse_hft_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HFTLinkStub(object):
    """-----------------------------------------------------------------------
    SERVICE DEFINITION
    -----------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/synapse.hft.HFTLink/Ping',
                request_serializer=synapse__hft__pb2.Empty.SerializeToString,
                response_deserializer=synapse__hft__pb2.SystemState.FromString,
                _registered_method=True)
        self.LoadScenario = channel.unary_unary(
                '/synapse.hft.HFTLink/LoadScenario',
                request_serializer=synapse__hft__pb2.ScenarioDefinition.SerializeToString,
                response_deserializer=synapse__hft__pb2.ScenarioStatus.FromString,
                _registered_method=True)
        self.SystemControl = channel.unary_unary(
                '/synapse.hft.HFTLink/SystemControl',
                request_serializer=synapse__hft__pb2.ControlCommand.SerializeToString,
                response_deserializer=synapse__hft__pb2.CommandResponse.FromString,
                _registered_method=True)
        self.StreamTraffic = channel.stream_unary(
                '/synapse.hft.HFTLink/StreamTraffic',
                request_serializer=synapse__hft__pb2.TrafficFrame.SerializeToString,
                response_deserializer=synapse__hft__pb2.SystemState.FromString,
                _registered_method=True)


class HFTLinkServicer(object):
    """-----------------------------------------------------------------------
    SERVICE DEFINITION
    -----------------------------------------------------------------------
    """

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadScenario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SystemControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTraffic(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HFTLinkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=synapse__hft__pb2.Empty.FromString,
                    response_serializer=synapse__hft__pb2.SystemState.SerializeToString,
            ),
            'LoadScenario': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadScenario,
                    request_deserializer=synapse__hft__pb2.ScenarioDefinition.FromString,
                    response_serializer=synapse__hft__pb2.ScenarioStatus.SerializeToString,
            ),
            'SystemControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SystemControl,
                    request_deserializer=synapse__hft__pb2.ControlCommand.FromString,
                    response_serializer=synapse__hft__pb2.CommandResponse.SerializeToString,
            ),
            'StreamTraffic': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTraffic,
                    request_deserializer=synapse__hft__pb2.TrafficFrame.FromString,
                    response_serializer=synapse__hft__pb2.SystemState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'synapse.hft.HFTLink', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('synapse.hft.HFTLink', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HFTLink(object):
    """-----------------------------------------------------------------------
    SERVICE DEFINITION
    -----------------------------------------------------------------------
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.hft.HFTLink/Ping',
            synapse__hft__pb2.Empty.SerializeToString,
            synapse__hft__pb2.SystemState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoadScenario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.hft.HFTLink/LoadScenario',
            synapse__hft__pb2.ScenarioDefinition.SerializeToString,
            synapse__hft__pb2.ScenarioStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SystemControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/synapse.hft.HFTLink/SystemControl',
            synapse__hft__pb2.ControlCommand.SerializeToString,
            synapse__hft__pb2.CommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTraffic(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/synapse.hft.HFTLink/StreamTraffic',
            synapse__hft__pb2.TrafficFrame.SerializeToString,
            synapse__hft__pb2.SystemState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
